### ISSUE TITLE
Add PVT_Benchmark and sector_benchmark to

### ISSUE THREAD

**Issue by SStolzman** [AZASRS/AZASRS#20]
Benchmark type is now set within its own table. We need to provide a use case in order to satisfy the requirements. Joining tables with a benchmark type will be much quicker. 

In order to see what's available you can run the function tbl_benchmark_type() which currently returns the following: 

```
  benchmark_type_id benchmark_type
              <int> <chr>         
1                 1 SAA           
2                 2 IMP           
3                 3 PVT           
4                 4 Sector  
```

**Comment by SStolzman** [comment]
It would be preferable not to have something such as `PVT_Benchmark" and `sector_benchmark` (especially with the inconsistency in capitalization). If we can find a way to wait until the data has been pulled to then pull it in as a tibble and do something such as a `pivot_wider()` function that would be much faster and would remove the need for loops.

**Comment by John-Doran** [comment]
To run PE Stats we need a method to assign a primary (which each fund must have) and sector benchmark (which many fund do have but not all) for each fund and then pull the proper benchmark data. 

Looking at your benchmark data, you seem to have a field for pm_fund_info_id, but this is simply a duplicate for pm_fund_info_id #1 and #2. This doesn't make sense to me. This table is huge simply because the DB is replicating identical benchmark data for most funds; here what we call "F8-LSTA"; which is simply a fixed 8% return bolted onto the S&P LSTA + 250 bps. Why don't we have only unique data in the benchmark table and index by and identifier, like benchmark_info_id? The credit funds only have two benchmarks at this point, so I am not sure we need this data replicated over and over. Also, I need a way to know what the benchmark_info_id actually is, like our naming convention for bench.lst. 

Our current list only contains 26 benchmarks and I am guessing some are not needed:
bench.lst %>% names()

The DB contains 68 unique benchmark_info_id's and 278 pm_fund_info_id's

For now, I will need to use a modified fund_info to find the primary and sector benchmarks:
fund_info_add <- read_csv("P:/IMD/zIMD Performance Database/output/pm_fund_info.csv") %>% 
  select(pm_fund_id, PVT_Benchmark, sector_benchmark )
fund_info <- AZASRS::get_pm_fund_info() %>% 
  left_join(fund_info_add, by = "pm_fund_id")

then index off bench.lst %>% names() as necessary.

**Comment by SStolzman** [comment]
I believe I have fixed this with an extra parameter to pass to the function:
`AZASRS::get_pm_fund_info(add_benchmark = TRUE)` -- This is in the latest release and has test coverage.
